# Generated by Django 5.1.1 on 2024-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=models.TextField(blank=True),
        ),
    ]
