# Generated by Django 5.1.1 on 2024-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0003_remove_video_video_file_video_file_video_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='subtitle_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='end_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitle',
            name='start_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
