# Generated by Django 5.1.1 on 2024-09-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0004_rename_subtitle_text_subtitle_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='language',
        ),
    ]
