# Generated by Django 5.1.1 on 2024-09-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0005_remove_subtitle_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
